# Generated by Django 4.2.26 on 2025-11-23

from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0920_alter_integration_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="sdk_config",
            field=models.JSONField(blank=True, null=True, validators=[posthog.models.utils.validate_sdk_config]),
        ),
    ]
