# Generated by Django 4.2.26 on 2025-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ee", "0031_agentartifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="tool_call_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
